name: Notify default project updates to sub-projects

on:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Default project
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#      - name: Build with Gradle
#        run: ./gradlew build

      - name: Trigger dependent projects
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.ORG_GITHUB_PAT }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/Mojise/github-actions-new-app-2/dispatches \
          -d '{"event_type":"default-update"}'
